/**
 * Format examples for the prompt: two from the reference workbook (file upload) and one from a
 * different domain (login). They show the Standard Test Case Format's structure and depth only —
 * the prompt tells the model to copy the format, not the content.
 */

export const FORMAT_EXAMPLES = [
  {
    id: "TC_RU_001",
    title: "Verify user is able to upload a valid PDF resume within the size limit",
    category: "Functional",
    type: "Positive",
    priority: "P1 - Critical",
    automation: "Yes",
    preconditions: [
      "CRM application is up and accessible in the QA environment.",
      "User is logged in with a role that has 'Upload Resume' permission (e.g., Recruiter / Admin).",
      "A candidate record exists and is opened in the Candidate Details page.",
      "Candidate record currently has NO resume attached.",
      "Required test files are prepared and available on the local machine.",
    ],
    steps: [
      "Navigate to CRM > Candidates and open the test candidate record.",
      "Go to the 'Resume' / 'Attachments' section.",
      "Click on the 'Upload Resume' button.",
      "In the OS file picker, browse and select the valid PDF file.",
      "Click 'Open' in the file picker.",
      "Click 'Upload' / 'Save' (if a separate confirm button exists).",
      "Observe the on-screen message and the Resume section.",
      "Refresh the page and re-check the Resume section.",
    ],
    testData: ["File name: Sample_Resume.pdf", "Format: PDF (text-based, 2 pages)", "Size: 1 MB (1,048,576 bytes)"],
    expectedResult: [
      "File picker closes and upload starts with a progress indicator/loader.",
      "Upload completes without any error.",
      "Success toast/message displayed, e.g., 'Resume uploaded successfully'.",
      "Resume section shows the uploaded file name with correct extension (.pdf), size (~1 MB) and upload date/time.",
      "After page refresh, the resume is still attached (data persisted in DB/storage).",
      "Download/preview icon is available for the uploaded file.",
    ],
  },
  {
    id: "TC_RU_007",
    title: "Verify file just above 5 MB (max + 1 byte) is rejected",
    category: "Boundary Value",
    type: "Negative",
    priority: "P1 - Critical",
    automation: "Yes",
    preconditions: [
      "CRM application is up and accessible in the QA environment.",
      "User is logged in with a role that has 'Upload Resume' permission (e.g., Recruiter / Admin).",
      "A candidate record exists and is opened in the Candidate Details page.",
      "Candidate record currently has NO resume attached.",
      "Required test files are prepared and available on the local machine.",
      "File size verified as 5,242,881 bytes.",
    ],
    steps: [
      "Navigate to CRM > Candidates and open the test candidate record.",
      "Go to the 'Resume' / 'Attachments' section.",
      "Click on the 'Upload Resume' button.",
      "In the OS file picker, browse and select the PDF file of 5,242,881 bytes.",
      "Click 'Open' in the file picker.",
      "Click 'Upload' / 'Save' (if a separate confirm button exists).",
      "Observe the on-screen message and the Resume section.",
      "Refresh the page and re-check the Resume section.",
    ],
    testData: ["File name: Resume_5MB_plus1.pdf", "Format: PDF", "Size: 5,242,881 bytes (5 MB + 1 byte)"],
    expectedResult: [
      "File is NOT uploaded.",
      "A clear inline/toast validation message is displayed: 'File size exceeds the maximum limit of 5 MB.'.",
      "Resume section remains unchanged (no file name, no broken/empty entry).",
      "After page refresh, no resume is attached to the record.",
      "No API call stores the file / no orphan file in storage.",
      "User can immediately retry with a valid file (UI not stuck/disabled).",
      "Validation should ideally happen on the client side before upload starts, and also be enforced by the server.",
    ],
  },
  {
    id: "TC_LGN_004",
    title: "Verify login is blocked after 5 consecutive wrong passwords",
    category: "Security",
    type: "Negative",
    priority: "P1 - Critical",
    automation: "Yes",
    preconditions: [
      "Web application is up and accessible in the QA environment.",
      "A registered, active test account exists.",
      "User is logged out and the Login page is open.",
      "Test account has 4 failed attempts recorded.",
      "Account lockout policy is enabled (5 attempts, 15 minutes).",
    ],
    steps: [
      "Open the Login page.",
      "Enter the registered email in the 'Email' field.",
      "Enter a wrong password in the 'Password' field and click 'Sign in' (attempt 5).",
      "Observe the message shown.",
      "Enter the correct password and click 'Sign in' again.",
      "Check the lockout entry in the security / audit log.",
    ],
    testData: ["Email: qa.user01@example.com", "Password: Wrong@123 (attempt 5)", "Then: Valid@1234 (correct password)"],
    expectedResult: [
      "After attempt 5, sign-in fails and no session is created.",
      "Message shown: 'Your account is locked for 15 minutes.'",
      "The correct password is also rejected while the account is locked.",
      "The message does not reveal whether the email or the password was wrong.",
      "The lockout is recorded in the audit log with the time and IP address.",
    ],
  },
];
