/**
 * Heuristics for attribute values that look generated by a framework or build
 * tool and are likely to change between builds or page loads.
 */
const PATTERNS: RegExp[] = [
  /\d{3,}/, // long number runs: item1234, row_20231004
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, // UUID
  /(^|[-_])[0-9a-f]{8,}($|[-_])/i, // long hex hashes
  /^(ember|ext-gen|ext-comp|gwt-uid|yui_|jsx-|j_idt)\d*/i, // framework ids: ember123, ext-gen45
  /^(mui|react-select|headlessui|radix|downshift|rc-tabs|mat-[a-z]+|cdk-[a-z]+|ng-tns|uid|id)-[\w-]*\d/i, // mui-45, mat-input-0
  /^:r[0-9a-z]+:$/i, // React useId: :r1:
  /^radix-:/i,
  /^(css|jss|sc|emotion)-[a-z0-9]{4,}$/i, // CSS-in-JS: css-1x2y3z, sc-bdVaJa
  /__[A-Za-z0-9_-]{5}$/, // CSS modules: Button_primary__3kX9a
];

/** Hashed CSS-module suffix such as btn_x7f3a (letters and digits mixed). */
function hasHashedSuffix(value: string) {
  const m = /[_-]([A-Za-z0-9]{4,8})$/.exec(value);
  if (!m) return false;
  const seg = m[1];
  return /\d/.test(seg) && /[A-Za-z]/.test(seg) && !/^[A-Za-z]+\d{1,2}$/.test(seg);
}

export function looksAutoGenerated(value: string | null | undefined): boolean {
  if (!value) return false;
  const v = value.trim();
  if (!v) return false;
  return PATTERNS.some((p) => p.test(v)) || hasHashedSuffix(v);
}
