import { JSDOM } from "jsdom";
import { describe, expect, it } from "vitest";

import { looksAutoGenerated } from "./autogen";
import { accessibleName, roleOf } from "./dom";
import { queryRole, queryText, testSelector } from "./match";
import { fieldName, pageObjectSnippets } from "./page-object";
import { cssValue, javaString, tsString, xpathLiteral } from "./quote";
import { recommendation, scoreCandidate, suggestLocators, type Candidate, type StrategyId } from "./strategies";
import { buildTree, elementAt, filterTree, findByText, pathOf, SAMPLE_HTML } from "./tree";

const docOf = (html: string) => new JSDOM(html).window.document;
const sample = () => docOf(SAMPLE_HTML);
const q = (doc: Document, css: string) => doc.querySelector(css)!;
const byStrategy = (cs: Candidate[], s: StrategyId) => cs.find((c) => c.strategy === s);

describe("quoting", () => {
  it("escapes Java and TS strings", () => {
    expect(javaString(`a "b" \\c`)).toBe(`"a \\"b\\" \\\\c"`);
    expect(tsString(`it's`)).toBe(`'it\\'s'`);
  });
  it("quotes CSS attribute values", () => {
    expect(cssValue("x'y")).toBe(`'x\\'y'`);
    expect(cssValue("x", '"')).toBe(`"x"`);
  });
  it("builds XPath literals, using concat() when both quotes appear", () => {
    expect(xpathLiteral("Sign in")).toBe("'Sign in'");
    expect(xpathLiteral("Don't")).toBe(`"Don't"`);
    expect(xpathLiteral(`Say "hi" don't`)).toBe(`concat('Say "hi" don', "'", 't')`);
    const doc = docOf(`<button>Say "hi" don't</button>`);
    expect(testSelector(doc, `//button[normalize-space()=${xpathLiteral(`Say "hi" don't`)}]`).elements).toHaveLength(1);
  });
});

describe("auto-generated values", () => {
  it.each(["ember123", "mui-45", "btn_x7f3a", "Button_primary__3kX9a", ":r1:", "css-1x2y3z", "a1b2c3d4e5f6", "row-20231004", "mat-input-0"])(
    "flags %s",
    (v) => expect(looksAutoGenerated(v)).toBe(true),
  );
  it.each(["email", "login-btn", "submit", "nav-item2", "user_name", "step-2", "btn-primary"])("accepts %s", (v) =>
    expect(looksAutoGenerated(v)).toBe(false),
  );
});

describe("roles and names", () => {
  it("computes implicit roles and accessible names", () => {
    const doc = sample();
    expect(roleOf(q(doc, "button[type=submit]"))).toBe("button");
    expect(roleOf(q(doc, "#email"))).toBe("textbox");
    expect(roleOf(q(doc, "a"))).toBe("link");
    expect(accessibleName(q(doc, "#email"))).toBe("Email");
    expect(accessibleName(q(doc, "input[type=checkbox]"))).toBe("Remember me");
    expect(accessibleName(docOf(`<button aria-label="Close"><svg/></button>`).querySelector("button")!)).toBe("Close");
  });
  it("matches getByRole names case-insensitively by substring", () => {
    const doc = sample();
    expect(queryRole(doc, "button", "sign")).toHaveLength(1);
    expect(queryRole(doc, "button", "Sign in", true)).toHaveLength(1);
  });
  it("matches getByText exactly at the deepest element", () => {
    const doc = docOf(`<div><span>Save</span></div><p>Save</p><p>Save all</p>`);
    expect(queryText(doc, "Save")).toHaveLength(2);
  });
});

describe("strategies", () => {
  it("ranks the test attribute first for the submit button", () => {
    const doc = sample();
    const cs = suggestLocators(q(doc, "button[type=submit]"));
    expect(cs[0].strategy).toBe("testAttr");
    expect(cs[0].score).toBeGreaterThanOrEqual(80);
    expect(cs[0].badge).toBe("Robust");
    expect(cs[0].playwright).toBe("page.getByTestId('login-btn')");
    expect(cs[0].selenium).toBe(`By.cssSelector("[data-testid='login-btn']")`);
    expect(byStrategy(cs, "role")?.playwright).toBe("page.getByRole('button', { name: 'Sign in' })");
    expect(byStrategy(cs, "text")?.selenium).toBe(`By.xpath("//button[normalize-space()='Sign in']")`);
    expect(byStrategy(cs, "relXpath")?.xpath).toBe("//form[@id='login']//button[@type='submit']");
    expect(byStrategy(cs, "absXpath")?.playwright).toBeUndefined();
  });

  it("builds ID, label, placeholder and name locators for an input", () => {
    const doc = sample();
    const cs = suggestLocators(q(doc, "#email"));
    expect(byStrategy(cs, "id")?.selenium).toBe(`By.id("email")`);
    expect(byStrategy(cs, "id")?.playwright).toBe(`page.locator('#email')`);
    expect(byStrategy(cs, "label")?.playwright).toBe("page.getByLabel('Email')");
    expect(byStrategy(cs, "label")?.xpath).toBe("//input[@id=//label[normalize-space()='Email']/@for]");
    expect(byStrategy(cs, "label")?.matches).toBe(1);
    expect(byStrategy(cs, "placeholder")?.playwright).toBe("page.getByPlaceholder('you@example.com')");
    expect(byStrategy(cs, "name")?.selenium).toBe(`By.name("email")`);
    expect(byStrategy(cs, "name")?.playwright).toBe(`page.locator('[name="email"]')`);
    expect(cs.every((c) => c.matches === 1)).toBe(true);
  });

  it("penalises auto-generated IDs and hashed classes", () => {
    const doc = sample();
    const cs = suggestLocators(q(doc, "#ember1042"));
    const id = byStrategy(cs, "id")!;
    expect(id.flags.autoGenerated).toBe(true);
    expect(id.score).toBe(60);
    expect(id.reason).toMatch(/auto-generated/);
    expect(cs[0].strategy).not.toBe("id");
  });

  it("detects non-unique locators and falls back to scoped or indexed CSS", () => {
    const doc = docOf(`<ul class="menu"><li><a href="#">Item</a></li><li><a href="#">Item</a></li></ul>`);
    const second = doc.querySelectorAll("a")[1];
    const cs = suggestLocators(second);
    const text = byStrategy(cs, "text")!;
    expect(text.matches).toBe(2);
    expect(text.reason).toBe("Matches 2 elements — not unique");
    const abs = byStrategy(cs, "absXpath")!;
    expect(abs.xpath).toBe("/html/body/ul/li[2]/a");
    expect(abs.flags.indexed).toBe(true);
  });

  it("recommends asking for data-testid when there is no stable hook", () => {
    const doc = docOf(`<div><span class="x">Hello</span></div>`);
    const el = q(doc, "span");
    expect(recommendation(el, suggestLocators(el)).tip).toMatch(/data-testid/);
    const btn = q(sample(), "button[type=submit]");
    expect(recommendation(btn, suggestLocators(btn)).tip).toBeNull();
  });
});

describe("scoring", () => {
  const base = { selenium: "", findBy: { using: "css" as const, value: "" }, flags: { autoGenerated: false, indexed: false, longText: false } };
  it("applies each adjustment", () => {
    expect(scoreCandidate({ ...base, strategy: "testAttr", css: "[data-testid='a']", matches: 1 }).score).toBe(100);
    expect(scoreCandidate({ ...base, strategy: "testAttr", css: "[data-testid='a']", matches: 3 }).score).toBe(55);
    expect(scoreCandidate({ ...base, strategy: "css", css: "x".repeat(40), matches: 1, flags: { ...base.flags, indexed: true } }).score).toBe(45);
    expect(scoreCandidate({ ...base, strategy: "text", xpath: "y".repeat(50), matches: 1, flags: { ...base.flags, longText: true } }).score).toBe(60);
  });
  it("assigns badges by score", () => {
    expect(scoreCandidate({ ...base, strategy: "id", css: "#a", matches: 1 }).badge).toBe("Robust");
    expect(scoreCandidate({ ...base, strategy: "css", css: "x".repeat(40), matches: 1 }).badge).toBe("OK");
    expect(scoreCandidate({ ...base, strategy: "absXpath", xpath: "/html", matches: 1 }).badge).toBe("Fragile");
  });
});

describe("page object snippets", () => {
  it("derives camelCase field names", () => {
    const doc = sample();
    expect(fieldName(q(doc, "button[type=submit]"))).toBe("signInButton");
    expect(fieldName(q(doc, "#email"))).toBe("emailInput");
    expect(fieldName(q(doc, "a"))).toBe("forgotPasswordLink");
    expect(fieldName(docOf(`<button data-testid="login-btn"><svg/></button>`).querySelector("button")!)).toBe("loginButton");
  });
  it("generates Java and TS fields for the top locator", () => {
    const doc = sample();
    const el = q(doc, "button[type=submit]");
    const { java, ts } = pageObjectSnippets(el, suggestLocators(el)[0]);
    expect(java).toContain(`@FindBy(css = "[data-testid='login-btn']")`);
    expect(java).toContain("private WebElement signInButton;");
    expect(java).toContain(`private static final By SIGN_IN_BUTTON = By.cssSelector("[data-testid='login-btn']");`);
    expect(ts).toBe("readonly signInButton = this.page.getByTestId('login-btn');");
  });
});

describe("tree and tester", () => {
  it("builds a tree with stable paths", () => {
    const doc = sample();
    const tree = buildTree(doc)!;
    expect(tree.tag).toBe("html");
    const btn = q(doc, "button[type=submit]");
    expect(elementAt(doc, pathOf(btn))).toBe(btn);
  });
  it("filters by text and interactive-only", () => {
    const tree = buildTree(sample())!;
    const filtered = filterTree(tree, "sign in", true)!;
    const flat: string[] = [];
    const walk = (n: typeof tree) => {
      if (!n.children.length) flat.push(n.tag);
      n.children.forEach(walk);
    };
    walk(filtered);
    expect(flat).toEqual(["button"]);
  });
  it("finds elements by visible text", () => {
    const doc = sample();
    expect(findByText(doc, "Sign in")).toBe(q(doc, "button[type=submit]"));
    expect(findByText(doc, "nothing like this")).toBeNull();
  });
  it("counts CSS and XPath matches and reports syntax errors", () => {
    const doc = sample();
    expect(testSelector(doc, "button").elements).toHaveLength(2);
    expect(testSelector(doc, "//input").elements).toHaveLength(3);
    expect(testSelector(doc, "xpath=//label").kind).toBe("xpath");
    expect(testSelector(doc, "button[").error).toMatch(/Invalid CSS selector/);
    expect(testSelector(doc, "//button[").error).toMatch(/Invalid XPath/);
  });
});
