import { looksAutoGenerated } from "./autogen";
import { accessibleName, labelTextOf, normalizeText, roleOf, tagOf, testAttrOf } from "./dom";
import { javaString, tsString } from "./quote";
import type { Candidate } from "./strategies";

const SUFFIX: Record<string, string> = {
  button: "Button",
  link: "Link",
  textbox: "Input",
  searchbox: "Input",
  spinbutton: "Input",
  combobox: "Select",
  listbox: "Select",
  checkbox: "Checkbox",
  radio: "Radio",
  heading: "Heading",
  img: "Image",
  tab: "Tab",
  dialog: "Dialog",
};

/** Words that already mean the suffix (login-btn → login + Button). */
const SUFFIX_ALIASES: Record<string, string[]> = {
  Button: ["btn", "button"],
  Link: ["link", "lnk"],
  Input: ["input", "field", "txt", "textbox"],
  Select: ["select", "dropdown", "combo"],
  Checkbox: ["checkbox", "chk", "cb"],
};

function words(s: string) {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w.toLowerCase());
}

function camel(ws: string[]) {
  return ws.map((w, i) => (i === 0 ? w : w[0].toUpperCase() + w.slice(1))).join("");
}

/** A camelCase field name from the element's text, label, id, name or test attribute. */
export function fieldName(el: Element): string {
  const role = roleOf(el);
  const suffix = SUFFIX[role ?? ""] ?? (tagOf(el) === "input" || tagOf(el) === "textarea" ? "Input" : "Element");
  const test = testAttrOf(el);
  const sources = [
    accessibleName(el),
    labelTextOf(el),
    normalizeText(el.getAttribute("placeholder")),
    el.getAttribute("id") && !looksAutoGenerated(el.getAttribute("id")) ? el.getAttribute("id")! : "",
    el.getAttribute("name") ?? "",
    test && !looksAutoGenerated(test.value) ? test.value : "",
  ];
  let ws = words(sources.find((s) => s && words(s).length > 0 && s.length <= 60) ?? "").slice(0, 4);
  const aliases = SUFFIX_ALIASES[suffix] ?? [suffix.toLowerCase()];
  while (ws.length && aliases.includes(ws[ws.length - 1])) ws = ws.slice(0, -1);
  if (!ws.length) ws = [tagOf(el)];
  let name = camel([...ws, suffix.toLowerCase()]);
  if (/^\d/.test(name)) name = `el${name[0].toUpperCase()}${name.slice(1)}`;
  return name;
}

const constantName = (field: string) => field.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

/** Page Object snippets for the top locator: Java (@FindBy + By constant) and TypeScript. */
export function pageObjectSnippets(el: Element, top: Candidate) {
  const field = fieldName(el);
  const { using, value } = top.findBy;
  const java = [
    `@FindBy(${using} = ${javaString(value)})`,
    `private WebElement ${field};`,
    "",
    `private static final By ${constantName(field)} = ${top.selenium};`,
  ].join("\n");
  const tsExpr = top.playwright ?? `page.locator(${tsString(`xpath=${top.xpath ?? ""}`)})`;
  const ts = `readonly ${field} = this.${tsExpr};`;
  return { field, java, ts };
}
