import { looksAutoGenerated } from "./autogen";
import {
  accessibleName,
  isElement,
  isFormControl,
  labelElementOf,
  labelTextOf,
  normalizeText,
  roleOf,
  sameTagIndex,
  tagOf,
  testAttrOf,
  textOf,
} from "./dom";
import { queryCss, queryLabel, queryPlaceholder, queryRole, queryText, queryXpath } from "./match";
import { cssValue, isCssIdent, javaString, tsString, xpathLiteral, type Quote } from "./quote";

export type StrategyId =
  | "testAttr"
  | "id"
  | "role"
  | "label"
  | "placeholder"
  | "name"
  | "text"
  | "css"
  | "relXpath"
  | "absXpath"
  | "ai";

export const STRATEGIES: Record<StrategyId, { label: string; base: number; reason: string }> = {
  testAttr: { label: "Test attribute", base: 95, reason: "Unique test attribute" },
  id: { label: "ID", base: 90, reason: "Unique, stable ID" },
  role: { label: "Role + accessible name", base: 85, reason: "Role and name — how users find it" },
  label: { label: "Label", base: 85, reason: "Linked label text" },
  placeholder: { label: "Placeholder", base: 75, reason: "Placeholder — may change with copy edits" },
  name: { label: "Name attribute", base: 75, reason: "Unique name attribute" },
  text: { label: "Visible text", base: 70, reason: "Visible text — may change with copy edits" },
  css: { label: "Short CSS", base: 60, reason: "Short CSS path" },
  relXpath: { label: "Relative XPath", base: 50, reason: "XPath anchored to a stable ancestor" },
  absXpath: { label: "Absolute XPath", base: 20, reason: "Absolute path — breaks on any layout change" },
  ai: { label: "AI suggestion", base: 70, reason: "Suggested by AI" },
};

export type Badge = "Robust" | "OK" | "Fragile";

export type Candidate = {
  strategy: StrategyId;
  label: string;
  /** Raw selectors (single-quoted values); a strategy has at least one. */
  css?: string;
  xpath?: string;
  selenium: string;
  /** Playwright TS expression starting with `page.`; absent for absolute XPath. */
  playwright?: string;
  /** How Selenium's @FindBy should reference it. */
  findBy: { using: "id" | "name" | "css" | "xpath"; value: string };
  matches: number;
  flags: { autoGenerated: boolean; indexed: boolean; longText: boolean };
  score: number;
  badge: Badge;
  reason: string;
};

type Draft = Omit<Candidate, "label" | "score" | "badge" | "reason">;

const LONG_TEXT = 40;
const MAX_NAME = 80;

/** Score a draft: base, then penalties/bonus, clamped to 0–100. */
export function scoreCandidate(d: Draft): Pick<Candidate, "score" | "badge" | "reason"> {
  const info = STRATEGIES[d.strategy];
  let score = info.base;
  const unique = d.matches === 1;
  if (!unique) score -= 40;
  if (d.flags.autoGenerated) score -= 30;
  if (d.flags.indexed) score -= 15;
  if (d.flags.longText) score -= 10;
  const raw = d.css ?? d.xpath ?? "";
  if (raw.length <= 30 && unique && !d.flags.autoGenerated && !d.flags.indexed) score += 5;
  score = Math.max(0, Math.min(100, score));

  let reason = info.reason;
  if (d.matches === 0) reason = "Matches nothing — check the selector";
  else if (!unique) reason = `Matches ${d.matches} elements — not unique`;
  else if (d.flags.autoGenerated) reason = "Looks auto-generated — may change between builds";
  else if (d.flags.indexed) reason = "Index-based — breaks if layout changes";
  else if (d.flags.longText) reason = "Long text — likely to change or be translated";

  return { score, badge: score >= 80 ? "Robust" : score >= 50 ? "OK" : "Fragile", reason };
}

const finish = (d: Draft): Candidate => ({ ...d, label: STRATEGIES[d.strategy].label, ...scoreCandidate(d) });

const noFlags = { autoGenerated: false, indexed: false, longText: false };

function safeCount(fn: () => Element[]) {
  try {
    return fn().length;
  } catch {
    return 0;
  }
}

/** CSS for a single attribute, e.g. [data-testid='x'] or tag[name="x"]. */
const attrCss = (name: string, value: string, q: Quote, tag = "") => `${tag}[${name}=${cssValue(value, q)}]`;

function cssDraft(
  strategy: StrategyId,
  build: (q: Quote) => string,
  doc: Document,
  flags = noFlags,
  extra: Partial<Draft> = {},
): Draft {
  const css = build("'");
  return {
    strategy,
    css,
    selenium: `By.cssSelector(${javaString(css)})`,
    playwright: `page.locator(${tsString(build('"'))})`,
    findBy: { using: "css", value: css },
    matches: safeCount(() => queryCss(doc, css)),
    flags,
    ...extra,
  };
}

function xpathDraft(strategy: StrategyId, build: (q: Quote) => string, doc: Document, flags = noFlags, extra: Partial<Draft> = {}): Draft {
  const xpath = build("'");
  return {
    strategy,
    xpath,
    selenium: `By.xpath(${javaString(xpath)})`,
    playwright: `page.locator(${tsString(`xpath=${build('"')}`)})`,
    findBy: { using: "xpath", value: xpath },
    matches: safeCount(() => queryXpath(doc, xpath)),
    flags,
    ...extra,
  };
}

/** Classes that look hand-written (not hashed / utility-generated). */
function stableClasses(el: Element) {
  return Array.from(el.classList).filter((c) => isCssIdent(c) && !looksAutoGenerated(c) && c.length <= 30);
}

/** A stable handle for an ancestor: #id, [data-testid], or tag.class (for CSS); null if none. */
function anchorFor(el: Element): { css: (q: Quote) => string; xpath: (q: Quote) => string } | null {
  const tag = tagOf(el);
  const test = testAttrOf(el);
  if (test && !looksAutoGenerated(test.value)) {
    return {
      css: (q) => attrCss(test.name, test.value, q),
      xpath: (q) => `//${tag}[@${test.name}=${xpathLiteral(test.value, q)}]`,
    };
  }
  const id = el.getAttribute("id");
  if (id && !looksAutoGenerated(id)) {
    return {
      css: (q) => (isCssIdent(id) ? `#${id}` : attrCss("id", id, q)),
      xpath: (q) => `//${tag}[@id=${xpathLiteral(id, q)}]`,
    };
  }
  return null;
}

function nearestAnchor(el: Element) {
  for (let p = el.parentElement; p && tagOf(p) !== "body" && tagOf(p) !== "html"; p = p.parentElement) {
    const a = anchorFor(p);
    if (a) return a;
  }
  return null;
}

/** tag + up to two stable classes + a distinguishing attribute. */
function shortCss(el: Element, q: Quote) {
  const tag = tagOf(el);
  let css = tag + stableClasses(el)
    .slice(0, 2)
    .map((c) => `.${c}`)
    .join("");
  for (const attr of ["type", "role", "name", "aria-label", "title"]) {
    const v = el.getAttribute(attr);
    if (v && !looksAutoGenerated(v) && v.length <= 40) {
      css += attrCss(attr, v, q);
      break;
    }
  }
  return css;
}

/** Nearest ancestor with stable classes, e.g. "form.login". */
function classAncestor(el: Element) {
  for (let p = el.parentElement; p && tagOf(p) !== "body"; p = p.parentElement) {
    const classes = stableClasses(p);
    if (classes.length) return `${tagOf(p)}.${classes[0]}`;
  }
  return null;
}

export function absoluteXpath(el: Element) {
  const parts: string[] = [];
  let indexed = false;
  for (let n: Element | null = el; n; n = n.parentElement) {
    const { index, ambiguous } = sameTagIndex(n);
    if (ambiguous) indexed = true;
    parts.unshift(ambiguous ? `${tagOf(n)}[${index}]` : tagOf(n));
  }
  return { xpath: `/${parts.join("/")}`, indexed };
}

/** All candidate locators for `el`, best first. */
export function suggestLocators(el: Element): Candidate[] {
  const doc = el.ownerDocument;
  const tag = tagOf(el);
  const drafts: Draft[] = [];

  // 1. Test attribute
  const test = testAttrOf(el);
  if (test) {
    const flags = { ...noFlags, autoGenerated: looksAutoGenerated(test.value) };
    const d = cssDraft("testAttr", (q) => attrCss(test.name, test.value, q), doc, flags);
    if (test.name === "data-testid") d.playwright = `page.getByTestId(${tsString(test.value)})`;
    d.xpath = `//*[@${test.name}=${xpathLiteral(test.value)}]`;
    drafts.push(d);
  }

  // 2. ID
  const id = el.getAttribute("id");
  if (id) {
    const flags = { ...noFlags, autoGenerated: looksAutoGenerated(id) };
    const d = cssDraft("id", (q) => (isCssIdent(id) ? `#${id}` : attrCss("id", id, q)), doc, flags);
    d.selenium = `By.id(${javaString(id)})`;
    d.findBy = { using: "id", value: id };
    d.xpath = `//*[@id=${xpathLiteral(id)}]`;
    drafts.push(d);
  }

  // 3. Role + accessible name
  const role = roleOf(el);
  const name = accessibleName(el);
  if (role && name && name.length <= MAX_NAME && !["presentation", "none", "generic"].includes(role)) {
    const aria = normalizeText(el.getAttribute("aria-label"));
    const ownText = textOf(el);
    const value = normalizeText(el.getAttribute("value"));
    const build = (q: Quote) =>
      aria === name
        ? `//${tag}[@aria-label=${xpathLiteral(aria, q)}]`
        : ownText === name
          ? `//${tag}[normalize-space()=${xpathLiteral(name, q)}]`
          : value === name
            ? `//${tag}[@value=${xpathLiteral(value, q)}]`
            : labelElementOf(el)
              ? labelXpath(el, name, q)
              : `//${tag}[@title=${xpathLiteral(name, q)}]`;
    const d = xpathDraft("role", build, doc, { ...noFlags, longText: name.length > LONG_TEXT });
    d.playwright = `page.getByRole(${tsString(role)}, { name: ${tsString(name)} })`;
    d.matches = safeCount(() => queryRole(doc, role, name));
    drafts.push(d);
  }

  // 4. Label (form controls)
  const labelText = labelTextOf(el);
  if (labelText && labelText.length <= MAX_NAME) {
    const d = xpathDraft("label", (q) => labelXpath(el, labelText, q), doc, { ...noFlags, longText: labelText.length > LONG_TEXT });
    d.playwright = `page.getByLabel(${tsString(labelText)})`;
    d.matches = safeCount(() => queryLabel(doc, labelText));
    drafts.push(d);
  }

  // 5. Placeholder
  const placeholder = normalizeText(el.getAttribute("placeholder"));
  if (placeholder) {
    const d = cssDraft("placeholder", (q) => attrCss("placeholder", el.getAttribute("placeholder")!, q, tag), doc, {
      ...noFlags,
      longText: placeholder.length > LONG_TEXT,
    });
    d.playwright = `page.getByPlaceholder(${tsString(placeholder)})`;
    d.xpath = `//${tag}[@placeholder=${xpathLiteral(el.getAttribute("placeholder")!)}]`;
    d.matches = safeCount(() => queryPlaceholder(doc, placeholder));
    drafts.push(d);
  }

  // 6. Name attribute
  const nameAttr = el.getAttribute("name");
  if (nameAttr && isFormControlOrButton(el)) {
    const d = cssDraft("name", (q) => attrCss("name", nameAttr, q), doc, { ...noFlags, autoGenerated: looksAutoGenerated(nameAttr) });
    d.selenium = `By.name(${javaString(nameAttr)})`;
    d.findBy = { using: "name", value: nameAttr };
    d.xpath = `//*[@name=${xpathLiteral(nameAttr)}]`;
    drafts.push(d);
  }

  // 7. Visible text
  const text = textOf(el);
  if (text && text.length <= MAX_NAME && !isFormControl(el) && el.children.length <= 3) {
    const d = xpathDraft("text", (q) => `//${tag}[normalize-space()=${xpathLiteral(text, q)}]`, doc, {
      ...noFlags,
      longText: text.length > LONG_TEXT,
    });
    d.playwright = `page.getByText(${tsString(text)}, { exact: true })`;
    d.matches = safeCount(() => queryText(doc, text));
    drafts.push(d);
  }

  // 8. Short CSS (tag + stable class/attrs), scoped to a class ancestor or indexed if needed
  {
    let build = (q: Quote) => shortCss(el, q);
    let indexed = false;
    if (safeCount(() => queryCss(doc, build("'"))) > 1) {
      const anc = classAncestor(el);
      if (anc && safeCount(() => queryCss(doc, `${anc} ${build("'")}`)) === 1) {
        const inner = build;
        build = (q) => `${anc} ${inner(q)}`;
      } else {
        const inner = build;
        const { index } = sameTagIndex(el);
        build = (q) => `${anc ? `${anc} ` : ""}${inner(q)}:nth-of-type(${index})`;
        indexed = true;
      }
    }
    drafts.push(cssDraft("css", build, doc, { ...noFlags, indexed }));
  }

  // 9. Relative XPath anchored to a stable ancestor
  const anchor = nearestAnchor(el);
  if (anchor) {
    const predicate = (q: Quote) => {
      const type = el.getAttribute("type");
      if (type) return `[@type=${xpathLiteral(type, q)}]`;
      if (text && text.length <= LONG_TEXT) return `[normalize-space()=${xpathLiteral(text, q)}]`;
      return "";
    };
    let build = (q: Quote) => `${anchor.xpath(q)}//${tag}${predicate(q)}`;
    let indexed = false;
    const hits = (() => {
      try {
        return queryXpath(doc, build("'"));
      } catch {
        return [];
      }
    })();
    if (hits.length > 1) {
      const pos = hits.indexOf(el) + 1;
      const inner = build;
      build = (q) => `(${inner(q)})[${pos}]`;
      indexed = true;
    }
    drafts.push(xpathDraft("relXpath", build, doc, { ...noFlags, indexed }));
  }

  // 10. Absolute XPath (last resort)
  {
    const abs = absoluteXpath(el);
    const d = xpathDraft("absXpath", () => abs.xpath, doc, { ...noFlags, indexed: abs.indexed });
    delete d.playwright;
    drafts.push(d);
  }

  const order = Object.keys(STRATEGIES) as StrategyId[];
  return drafts
    .map(finish)
    .sort((a, b) => b.score - a.score || order.indexOf(a.strategy) - order.indexOf(b.strategy));
}

/**
 * A candidate from an external (AI) suggestion: checked against the parsed
 * document and scored like the others. `matchesTarget` is false when it
 * doesn't select the element at all.
 */
export function candidateFromSelector(
  el: Element,
  kind: "css" | "xpath",
  selector: string,
  aiReason: string,
): (Candidate & { matchesTarget: boolean }) | null {
  const doc = el.ownerDocument;
  let hits: Element[];
  try {
    hits = kind === "css" ? queryCss(doc, selector) : queryXpath(doc, selector);
  } catch {
    return null;
  }
  const flags = {
    autoGenerated: (selector.match(/[\w-]+/g) ?? []).some((t) => t.length > 3 && looksAutoGenerated(t)),
    indexed: /:nth-|\[\d+\]/.test(selector),
    longText: false,
  };
  const draft: Draft =
    kind === "css"
      ? {
          strategy: "ai",
          css: selector,
          selenium: `By.cssSelector(${javaString(selector)})`,
          playwright: `page.locator(${tsString(selector)})`,
          findBy: { using: "css", value: selector },
          matches: hits.length,
          flags,
        }
      : {
          strategy: "ai",
          xpath: selector,
          selenium: `By.xpath(${javaString(selector)})`,
          playwright: `page.locator(${tsString(`xpath=${selector}`)})`,
          findBy: { using: "xpath", value: selector },
          matches: hits.length,
          flags,
        };
  const c = finish(draft);
  const matchesTarget = hits.includes(el);
  if (!matchesTarget) return { ...c, score: 0, badge: "Fragile", reason: "Doesn't select this element", matchesTarget };
  return { ...c, reason: c.reason === STRATEGIES.ai.reason ? aiReason.slice(0, 140) || c.reason : c.reason, matchesTarget };
}

function isFormControlOrButton(el: Element) {
  return isFormControl(el) || tagOf(el) === "button";
}

/** XPath to a control through its label: via label[for] or a wrapping label. */
function labelXpath(el: Element, labelText: string, q: Quote) {
  const label = labelElementOf(el);
  const tag = tagOf(el);
  const lit = xpathLiteral(labelText, q);
  if (label && label.getAttribute("for") && label.getAttribute("for") === el.getAttribute("id")) {
    return `//${tag}[@id=//label[normalize-space()=${lit}]/@for]`;
  }
  return `//label[normalize-space()=${lit}]//${tag}`;
}

/** The top recommendation plus a tip when the element has no stable hook. */
export function recommendation(el: Element, candidates: Candidate[]) {
  const best = candidates[0];
  const hasStableHook = candidates.some(
    (c) => (c.strategy === "testAttr" || c.strategy === "id") && c.matches === 1 && !c.flags.autoGenerated,
  );
  const tip = hasStableHook
    ? null
    : `Ask developers to add \`data-testid\` to this <${tagOf(el)}> so tests don't depend on text or layout.`;
  return { best, tip };
}

export { isElement };
